namespace Dentiva.Core.Entities;
public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime? UpdatedAt { get; set; } }
public sealed class Clinic : Entity { public required string Name { get; set; } public string? DentistName { get; set; } public string? Phone { get; set; } public string? Address { get; set; } public string Currency { get; set; } = "BDT"; }
public sealed class User : Entity { public required string DisplayName { get; set; } public required string Login { get; set; } public required string PasswordHash { get; set; } public bool IsActive { get; set; } = true; public Guid? RoleId { get; set; } }
public sealed class Role : Entity { public required string Name { get; set; } public ICollection<Permission> Permissions { get; set; } = []; }
public sealed class Permission : Entity { public required string Code { get; set; } public Guid RoleId { get; set; } }
public sealed class Patient : Entity { public required string PatientCode { get; set; } public required string FullName { get; set; } public string? PreferredName { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public DateOnly? DateOfBirth { get; set; } public string? Gender { get; set; } public string Status { get; set; } = "Active"; public string? Notes { get; set; } public bool IsArchived { get; set; } }
public sealed class PatientMedicalHistory : Entity { public Guid PatientId { get; set; } public string? Allergies { get; set; } public string? Conditions { get; set; } public string? Medications { get; set; } }
public sealed class Visit : Entity { public Guid PatientId { get; set; } public DateTime VisitAt { get; set; } = DateTime.UtcNow; public string? ChiefComplaint { get; set; } public string? Diagnosis { get; set; } public string? Findings { get; set; } public string? ClinicalNote { get; set; } public DateOnly? FollowUpDate { get; set; } }
public sealed class Appointment : Entity { public Guid PatientId { get; set; } public DateTime StartsAt { get; set; } public int SerialNumber { get; set; } public string Status { get; set; } = "Scheduled"; public string? Reason { get; set; } }
public sealed class TreatmentPlan : Entity { public Guid PatientId { get; set; } public string Name { get; set; } = "Treatment plan"; public string Status { get; set; } = "Planned"; public ICollection<TreatmentPlanItem> Items { get; set; } = []; }
public sealed class TreatmentPlanItem : Entity { public Guid TreatmentPlanId { get; set; } public string Procedure { get; set; } = ""; public string? Tooth { get; set; } public decimal EstimatedPrice { get; set; } public string Status { get; set; } = "Planned"; }
public sealed class ToothCondition : Entity { public Guid PatientId { get; set; } public string ToothCode { get; set; } = ""; public string Condition { get; set; } = ""; public DateTime RecordedAt { get; set; } = DateTime.UtcNow; }
public sealed class Prescription : Entity { public Guid PatientId { get; set; } public Guid? VisitId { get; set; } public string? Advice { get; set; } public ICollection<PrescriptionItem> Items { get; set; } = []; }
public sealed class PrescriptionItem : Entity { public Guid PrescriptionId { get; set; } public string Medicine { get; set; } = ""; public string? Dosage { get; set; } public string? Frequency { get; set; } public string? Duration { get; set; } }
public sealed class Invoice : Entity { public required string InvoiceNumber { get; set; } public Guid PatientId { get; set; } public decimal Subtotal { get; set; } public decimal Discount { get; set; } public decimal Total { get; set; } public string Status { get; set; } = "Unpaid"; public ICollection<InvoiceItem> Items { get; set; } = []; public ICollection<Payment> Payments { get; set; } = []; }
public sealed class InvoiceItem : Entity { public Guid InvoiceId { get; set; } public string Description { get; set; } = ""; public decimal Quantity { get; set; } = 1; public decimal UnitPrice { get; set; } public decimal Total => Quantity * UnitPrice; }
public sealed class Payment : Entity { public Guid InvoiceId { get; set; } public decimal Amount { get; set; } public string Method { get; set; } = "Cash"; public string? Reference { get; set; } }
public sealed class Expense : Entity { public string Category { get; set; } = "Other"; public decimal Amount { get; set; } public DateOnly Date { get; set; } = DateOnly.FromDateTime(DateTime.Today); public string? Notes { get; set; } }
public sealed class Staff : Entity { public required string Name { get; set; } public string Role { get; set; } = "Staff"; public string? Phone { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Attachment : Entity { public Guid PatientId { get; set; } public string OriginalName { get; set; } = ""; public string StoredName { get; set; } = ""; public string Category { get; set; } = "Other"; public long Size { get; set; } }
public sealed class AuditLog : Entity { public Guid? UserId { get; set; } public string Action { get; set; } = ""; public string EntityName { get; set; } = ""; public Guid? RecordId { get; set; } }
